
(* whitespace is obvious, i can't be assed writing out all of it's locations *)

body = {expression};

expression = location, [insert, assign], ';';

location = [clone, '.'], location_segment, {'.', location_segment};
location_segment = identifier, [call];
clone = '|', location, '|';

identifier = ('_' | letter), {character};
call = '(', [formula, {',', formula}], ')';

insert = '->', location;

assign = ('=' | compound_assignment), formula;
compound_assignment = binary_operator, '=';

formula = value, {binary_operator, value};

value = number
      | string
      | boolean
      | 'null'
      | group
      | location
      | call
      | unary_operation
      | definition
      ;

number = digit, {digit}, ['.', digit, {digit}];
string = quote, {character - ? matched quote ?}, quote;
quote = '"' | "'";
boolean = 'true' | 'false';
group = '(', formula, ')';
unary_operation = unary_operator, location;

definition = [parameters], '{', body, '}';
parameters = '(', identifier, {',', identifier}, ')';

unary_operator = '!', '-';
binary_operator = '+', '-', '*', '/';

character = ? any printable character ?;
letter = ? /[a-zA-Z]/ ?;
digit = ? /[0-9]/ ?;